services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: currency_user
      POSTGRES_PASSWORD: currency_pass
      POSTGRES_DB: currency_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U currency_user -d currency_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    command: >
      sh -c "alembic -c currency_converter/alembic.ini upgrade head && uvicorn currency_converter.app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://currency_user:currency_pass@db:5432/currency_db
      CURRENCY_API_KEY: cur_live_DOjRKrVtI643qNaKji9FvkJwmoFEVU31XmtZlxP1
      CURRENCY_API_URL: https://app.currencyapi.com/
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
    depends_on:
      app:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pgdata: